numba/numba-scfg

numba_rvsdg/tests/simulator.py

This simplifies the `run*` methods in the simulator such that only a
`Label` and not both `Label` and `BasicBlock` must be supplied. The
Simulator received a new attribute `region_stack` which memoizes the
current region and allows for a region aware `get_block` for any
simulator run. This significantly reduces code overhead and creates a
simple, easy to use API when iterating through the program.
depends on #14

Simulator api

---

numba_rvsdg/core/datastructures/block_map.py
numba_rvsdg/tests/test_block_map.py
numba_rvsdg/tests/test_blockmap.py
numba_rvsdg/tests/test_transforms.py
numba_rvsdg/tests/test_utils.py

As titled, this PR makes the `from_yaml` method a staticmethod on `BlockMap`. Also adds a deserializer to convert `BlockMap` to yaml and a similar conversion in dictionary format as well.

Added yaml and dictionary conversion methods to BlockMap

---

numba_rvsdg/core/datastructures/labels.py
numba_rvsdg/tests/test_byteflow.py

Adds the typing signatures to the NameGenerator, adds numpydoc compatible documentation and does some refactoring on the code, mostly variable names and shortening one construct.

add typing and refactor NameGenerator

---

numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/core/transformations.py

We add some documentation, fixup the typing signature, refactor the function to use return sorted lists, modify some implementation details and add comments to the function. We return sorted lists, because we have been bitten in the past by using sets and them being unordered.

refactor find_headers_and_entries

---

numba_rvsdg/tests/simulator.py
numba_rvsdg/tests/test_simulate.py

The simulator based tests now trace the SCFG, and ensure that all test cases will have visited all blocks in the SCFG. This can help during test authoring to ensure full test coverage.

Add tracing to simulator tests

---

README.md

fixup formatting and typos in README

---

numba_rvsdg/core/transformations.py

This fixes two bugs on `main` introduced by:
* https://github.com/numba/numba-rvsdg/pull/26
and
* https://github.com/numba/numba-rvsdg/pull/28
It's probably a sign that the test coverage isn't high enough yet.

fix two bugs leftover from refactoring

---

.pre-commit-config.yaml

As titled. This PR adds pre-commit capabilites to this repository.
Note: We would need another PR with `pre-commit run --all` which re-formats a lot of files and throws type-errors from `mypy`. Once we have that PR running (the `mypy` and formatting errors fixed), we can add pre-commit as a workflow in `numba-rvsdg`

Added precommit configuration file

---

pyproject.toml

Currently `pip install .` produces an empty package.
This fixes it. I'm just following this page: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery

Fix package by enabling auto discovery.

---

numba_rvsdg/core/transformations.py
numba_rvsdg/tests/test_transforms.py

Fixes #45
Headers of multi-block loops that have a backedge to themselves, didn't have this processed.
The case of:
`label not in doms[jt]`
accounts for the case, where there were multiple entry edges into the loop and the original header has been replaced with a synthetic one.
An alternative fix would have been to simply delete this check, but then this breaks the test case `test_double_header` (after hacking the followup issues). This fix is non-intrusive and a test for the edge cases has been added too.

fixup case of backedge from header to header

---

numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/tests/simulator.py

The `insert_SyntheticFill` method was returning a `SyntheticReturn`, rather than a `SyntheticFill`, which does exist.
This fixes that method and adds support for `SyntheticFill` to the simulator for testing purposes.

fix insert_SyntheticFill

---

numba_rvsdg/core/datastructures/basic_block.py
numba_rvsdg/core/datastructures/byte_flow.py
numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/core/transformations.py
numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/simulator.py
numba_rvsdg/tests/test_scc.py
numba_rvsdg/tests/test_scfg.py
numba_rvsdg/tests/test_transforms.py

As titled,
This PR makes the following major changes:
- It adds a region hierarchy by the use of `SCFG.parent_region` and `SCFG.regions`
- For any SCFG that we create independently, a 'meta-region' is generated automatically which can be used to refer to the graph as a whole. 
- During transformations like `loop_restructuring` and `branch_restructuring` every new region created has itself declared as the `parent_region` in the corresponding subregion SCFG.
- `loop_restructuring` and `branch_restructuring` now take regions (`RegionBlock`) as arguments instead of graphs (`SCFG`s). To do the transformation on an entire graph, we can simply provide the `meta-region` of the graph instead.
- `RegionBlock`s are now referred to using their own independent names. They are no longer referred using …

Added region hierarchy and unique naming reference for RegionBlocks in SCFGs

---

numba_rvsdg/core/transformations.py

Fixes #46
The problem was that, in case of a multi-header loop with a single exit, the control-variable wasn't being setup correctly.
A further problem is that, even though this was tested, only the overall block structure of the SCFG was being compared. However the instructions of the blocks themselves were not, so this went unnoticed.
The fix for the test is to add the instructions contained within blocks to the YAML and then we can test this properly.

fix missing variable assignment

---

numba_rvsdg/core/datastructures/byte_flow.py
numba_rvsdg/core/transformations.py
numba_rvsdg/core/utils.py
numba_rvsdg/rendering/rendering.py

As titled,
This PR patches all calls to `logging.basicConfig` and orphan `print` statements used for debugging purposes.

Patching debug logging calls and debug print statements

---

.github/workflows/release.yml
docs/source/release_notes.rst
pyproject.toml

The 0.0.3 release failed because of multiple human errors, so these are the fixups that resulted from the learnings.
a) The version number must be set in the `pyproject.toml`
b) The `release.yml` workflow was detecting tags with `v` prefix
c) The release notes were updated to indicate the 0.0.3 failure and now releasing as 0.0.4 instead.

Fixups 0.0.4

---

.github/workflows/release.yml

The tags for the numba-rvsdg project don't use a "v" as prefix. We remove this and encase the regex in quotes to ensure it is valid YAML.

fix regex when detecting tags

---

docs/source/release_notes.rst

Updates via the `release_0.0.5` branch.

update release_notes for 0.0.4 and 0.0.5

---

numba_rvsdg/core/utils.py
numba_rvsdg/tests/simulator.py

As titled,
This PR adds a fixes for the simulator tests that fail during shift to Python 3.12.

Simulator test fixes for Python 3.12 version upgrade

---

README.md
makefile

The README now contains instructions based on the current state of the available dependencies for Python 3.12. All of these are now available from conda and no additional packages need to be installed via pip.
The makefiles is largely self-explanatory and contains all the low level commands to build the project, run all the tests and to render the documentation. It serves as a common entry-point for developers and services alike.

update REAMDE and add makefile

---

numba_rvsdg/core/datastructures/byte_flow.py
numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/test_figures.py
numba_rvsdg/tests/test_scc.py
numba_rvsdg/tests/test_scfg.py
numba_rvsdg/tests/test_simulate.py

This moves the loop and branch restructuring code from the `ByteFlow` class to the `SCFG` class. The `ByteFlow` class is scheduled for eventual deletion anyway -- so this is a first step in that direction.
This is needed now, such that `SCFG` generated from Python abstract syntax trees can also be transformed.

enable `scfg.restructure()`

---

numba_rvsdg/__init__.py
numba_rvsdg/core/datastructures/ast_transforms.py
numba_rvsdg/core/datastructures/basic_block.py
numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/test_ast_transforms.py

AST: Python Abstract Synatx Tree
(S)CFG: (Structured) Control Flow Graph
Items to note for reviewers:
* Most of changes are in the `ast_transforms.py` module which contains the meat of the implementation.
* Temporary data structures are created for a pure AST based CFG (`ASTCFG`) with blocks that are writable. This made it much easier to implement the builder pattern. They can easily be converted to a SCFG using the `ASTCFG.to_SCFG()` function.
* The `AST2SCFGTranformer` is stateful and is populated with housekeeping data structures post transform.
* The tests are all in `test_ast_transforms.py`. They are of the usual format: Python function as input and serialized graph to compare to.
* The tests also check the values of the unreachable and empty nodes that have been pruned from the CFG. …

implementation of an AST -> SCFG transformer

---

.github/workflows/test.yml
.pre-commit-config.yaml
makefile

CI Updates

---

docs/source/reference/datastructures.rst
numba_rvsdg/core/datastructures/ast_transforms.py

So that they render and read well as HTML.

Fixup ast_transform docs

---

makefile
numba_rvsdg/__init__.py
numba_rvsdg/core/datastructures/ast_transforms.py
numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/tests/test_ast_transforms.py
numba_rvsdg/tests/test_figures.py
numba_rvsdg/tests/test_rendering.py

This implements the creation of Python source code from a potentially restructured SCFG.
The main entry-point is:
```
from numba_rvsdg import SCFG2AST
```
And the round-trip test for the entry-points shows how to use the API:
```
class TestEntryPoints(TestCase):
def test_rondtrip(self):
def function() -> int:
x = 0
for i in range(2):
x += i
return x, i
scfg = AST2SCFG(function)
scfg.restructure()
ast_ = SCFG2AST(function, scfg)
exec_locals = {}
exec(ast.unparse(ast_), {}, exec_locals)
transformed = exec_locals["transformed_function"]
assert function() == transformed()
```
Special attention was paid to the testing of the transform. For all the previously defined testing functions to test the AST -> SCFG direction, the tests were augmented to also test the SCFG -> AST direction. To test a …

implement and test SCFG->AST conversion

---

numba_rvsdg/core/transformations.py

Fixes #139 
This makes sure that the comparison between strings is `==` and not `is` -- which then leads to the correct output, both branching regions have their jump targets updated accrodingly.

fix updating jump_targets in simple example

---

numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/test_rendering.py

This updates the rendering code for Python source based SCFGs such that the layout of the information inside the nodes has redundancies reduced and there is sufficient whitespace to visually segment the information contained within the nodes.
Before:
After:

Enhance rendering SCFGs

---

numba_rvsdg/core/datastructures/ast_transforms.py

Instead of every transformed function being called `transformed_function`, it is now called `transformed_ORIGINAL` where `ORIGINAL` is the original name of the function.
The tests do not need to be updated, because all the test functions are called `function` already.

improve name of transformed function

---

numba_rvsdg/core/datastructures/ast_transforms.py

While we expect that all `__loop_cont__` variables are used in the correct scope, adding a version number to the variable will help when debugging nested loops.
The tests do not fail for this change, because we don't ever check the transformed Python against a pre-recorded variant.

version __loop_cont__ variable

---

numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/test_rendering.py

Using the instructions at:
https://davidmathlogic.com/colorblind/#%23648FFF-%23785EF0-%23DC267F-%23FE6100-%23FFB000
I opted to use the IBM palette.
[old_colors.pdf](https://github.com/user-attachments/files/17192896/old_colors.pdf)
[new_colors.pdf](https://github.com/user-attachments/files/17192899/new_colors.pdf)

Use colors that are accessible for color blind

---

numba_rvsdg/core/datastructures/ast_transforms.py

remove outdated doc

---

numba_rvsdg/core/datastructures/ast_transforms.py
numba_rvsdg/tests/test_ast_transforms.py

implement handling and/or expressions

---

docs/source/release_notes.rst

Cherry-pick the 0.0.8 changelog for `main` and fixup the dates of the previous releases.

Cherry pick/changelog 0.0.8

---

renovate.json

So e.g. `actions/checkout@v4` is update to `actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2`
For more context see:
* Enable pinDigest to convert a major version to semver renovatebot/renovate#21901
* https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigeststosemver
Protects against attacks where version tags get mutated to point to malicious code to e.g. extract secrets via gh accounts be compromised.

Enable renovate to pin Actions to sha1 and semver
