byteflow2.py
example.py
simulator.py
test_byteflow2.py

port to python 3.11

---

byteflow2.py
test_simulate.py
testing.py

fix TestLoopRotate

---

numba_rvsdg/tests/testing.py

fix test formatting

---

Makefile

Remove makefile

---

numba_rvsdg/rendering/rendering.py

'\l' is to be used when rendering dot files

fix rendering

---

numba_rvsdg/tests/simulator.py

adding numpydoc based docs for the simulator

---

README.md

Following #7 this updates the README

update README post refactor

---

numba_rvsdg/tests/simulator.py

This makes the simulator a little more coherent.

update simulator argument name, order and types

---

numba_rvsdg/core/datastructures/basic_block.py
numba_rvsdg/core/datastructures/block_map.py
numba_rvsdg/tests/simulator.py
numba_rvsdg/tests/test_block_map.py

This is a region aware SCFG graph iterator. It will recurse into regions as appropriate.

Graph iter

---

numba_rvsdg/core/datastructures/labels.py
numba_rvsdg/core/transformations.py
numba_rvsdg/tests/simulator.py

remove some remnants of the SyntheticForIter construct

---

numba_rvsdg/core/transformations.py

As title. Variable name changes and reformatting.

Cosmetic refactor transformations

---

numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/core/transformations.py

Adding documentation, slight internal refactor, change return signature to be sorted lists. Also, refactored all uses of the function to account for the change in return signature.

refactor find_exiting_and_exits

---

numba_rvsdg/core/datastructures/scfg.py

fix set intialization in region iterator

---

numba_rvsdg/core/datastructures/flow_info.py
numba_rvsdg/core/datastructures/scfg.py

Fix conversion of out_targets in implicit jumps.
Depends on #34 so please merge that first.

Fix python ingestion

---

numba_rvsdg/core/datastructures/flow_info.py
numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/core/transformations.py
numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/test_byteflow.py
numba_rvsdg/tests/test_scfg.py
numba_rvsdg/tests/test_transforms.py

Seperated out regions from blocks

---

numba_rvsdg/core/datastructures/flow_info.py
numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/simulator.py
numba_rvsdg/tests/test_byteflow.py
numba_rvsdg/tests/test_fig3.py
numba_rvsdg/tests/test_fig4.py

This re-enabled testing fig. 3 and fig. 4 from the Bahmann paper. The output must still be inspected by a human, but any program crashes due to exceptions would be noticed.

Test rendering

---

numba_rvsdg/rendering/rendering.py

Fixes broken `renderer` on `main`.

fix missing refactor of region.exiting

---

.readthedocs.yaml
docs/source/conf.py

Adding .readthedocs.yaml

---

.pre-commit-config.yaml
numba_rvsdg/core/datastructures/basic_block.py
numba_rvsdg/core/datastructures/block_names.py
numba_rvsdg/core/datastructures/byte_flow.py
numba_rvsdg/core/datastructures/flow_info.py
numba_rvsdg/core/datastructures/scfg.py
numba_rvsdg/core/transformations.py
numba_rvsdg/core/utils.py
numba_rvsdg/networkx_vendored/scc.py
numba_rvsdg/rendering/rendering.py
numba_rvsdg/tests/mock_asm.py
numba_rvsdg/tests/simulator.py
numba_rvsdg/tests/test_byteflow.py
numba_rvsdg/tests/test_fig4.py
numba_rvsdg/tests/test_mock_asm.py
numba_rvsdg/tests/test_scc.py
numba_rvsdg/tests/test_scfg.py
numba_rvsdg/tests/test_transforms.py
numba_rvsdg/tests/test_utils.py

This PR re-adds the pre-commit configuration from the `experimental` branch onto the main branch.
Currently, this is not a CI test and can be used as a formatting check locally before committing any changes. 
Note: Running this for the first time may have library-wide changes due to `black`, this can be disabled locally by configuring pre-commit to not use it.

Added pre commit configuration

---

.github/workflows/release.yml
.github/workflows/test.yml

Create a GitHub Action to build wheels

---

conda-recipes/bld.bat
conda-recipes/build.sh
conda-recipes/meta.yaml

Closes https://github.com/numba/numba-rvsdg/issues/86.
Sample OSX packages are at: https://anaconda.org/sklam/numba_rvsdg/files

Add conda-recipe

---

docs/source/release_notes.rst

adding release notes for 0.0.3

---

docs/source/conf.py
pyproject.toml

This will be the next development version, so we set that now.

set version to 0.0.6-dev0

---

numba_rvsdg/core/transformations.py

remove print left over from debugging

---

.github/workflows/test.yml

use default shell
